version: '3'

services:
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ../src:/var/www/app
    networks:
      - app-net

  nginx:
    build:
      context: ./nginx
    volumes:
      - ../src:/var/www/app
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-net

  database:
    build:
      context: ./database
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=docker
    volumes:
      - ./database/data:/var/lib/mysql/data
    networks:
      - app-net

#  postgres:
#    build:
#      context: ./postgres
#    environment:
#      POSTGRES_PASSWORD: example
#      POSTGRES_USER: puser
#      POSTGRES_DB: pdb
#      PGDATA: /var/lib/postgresql/data
#    volumes:
#      - ./postgres/data:/var/lib/postgresql/data
#    networks:
#      - app-net

#Docker Networks
networks:
  app-net:
    driver: bridge